/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:slider1:657926:
 // println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider1:657926:

public void slider2_change1(GSlider source, GEvent event) { //_CODE_:slider2:673304:
  //println("slider2 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider2:673304:

public void slider3_change1(GSlider source, GEvent event) { //_CODE_:slider3:210125:
  //println("slider3 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider3:210125:

public void slider4_change1(GSlider source, GEvent event) { //_CODE_:slider4:266660:
  //println("slider4 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider4:266660:

public void slider5_change1(GSlider source, GEvent event) { //_CODE_:slider5:389983:
 // println("slider5 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider5:389983:

public void slider6_change1(GSlider source, GEvent event) { //_CODE_:slider6:472841:
  //println("slider6 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider6:472841:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:285984:
  //println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
  if(keyPressed){
    if(key==ENTER){
  interpolationconstant = textfield1.getText();
    }
  }
} //_CODE_:textfield1:285984:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:692548:
  if(keyPressed){
    if(key==ENTER){
  interpolationconstant2 = textfield2.getText();
    }
  }
  //println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield2:692548:

public void slider7_change1(GSlider source, GEvent event) { //_CODE_:slider7:773085:
  println("slider7 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider7:773085:

public void slider8_change1(GSlider source, GEvent event) { //_CODE_:slider8:330027:
  println("slider8 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider8:330027:

public void slider9_change1(GSlider source, GEvent event) { //_CODE_:slider9:651894:
  println("slider9 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider9:651894:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.PURPLE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  slider1 = new GSlider(this, 60, 350, 200, 50, 10.0);
  slider1.setShowValue(true);
  slider1.setShowLimits(true);
  slider1.setLimits(0.0, 0.0, 1.0);
  slider1.setNbrTicks(11);
  slider1.setEasing(4.0);
  slider1.setNumberFormat(G4P.DECIMAL, 2);
  slider1.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  slider1.setOpaque(false);
  slider1.addEventHandler(this, "slider1_change1");
  label1 = new GLabel(this, 252, 12, 474, 43);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("FINAL YEAR PROJECT - FACE CONTROLLER");
  label1.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label1.setOpaque(true);
  slider2 = new GSlider(this, 60, 384, 200, 50, 10.0);
  slider2.setShowValue(true);
  slider2.setShowLimits(true);
  slider2.setLimits(0.0, 0.0, 1.0);
  slider2.setEasing(4.0);
  slider2.setNumberFormat(G4P.DECIMAL, 2);
  slider2.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  slider2.setOpaque(false);
  slider2.addEventHandler(this, "slider2_change1");
  slider3 = new GSlider(this, 60, 422, 200, 50, 10.0);
  slider3.setShowValue(true);
  slider3.setShowLimits(true);
  slider3.setLimits(0.0, 0.0, 1.0);
  slider3.setEasing(4.0);
  slider3.setNumberFormat(G4P.DECIMAL, 2);
  slider3.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  slider3.setOpaque(false);
  slider3.addEventHandler(this, "slider3_change1");
  slider4 = new GSlider(this, 60, 458, 200, 50, 10.0);
  slider4.setShowValue(true);
  slider4.setShowLimits(true);
  slider4.setLimits(0.0, 0.0, 1.0);
  slider4.setEasing(4.0);
  slider4.setNumberFormat(G4P.DECIMAL, 2);
  slider4.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  slider4.setOpaque(false);
  slider4.addEventHandler(this, "slider4_change1");
  slider5 = new GSlider(this, 60, 494, 200, 50, 10.0);
  slider5.setShowValue(true);
  slider5.setShowLimits(true);
  slider5.setLimits(0.0, 0.0, 1.0);
  slider5.setEasing(4.0);
  slider5.setNumberFormat(G4P.DECIMAL, 2);
  slider5.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  slider5.setOpaque(false);
  slider5.addEventHandler(this, "slider5_change1");
  slider6 = new GSlider(this, 60, 530, 200, 50, 10.0);
  slider6.setShowValue(true);
  slider6.setShowLimits(true);
  slider6.setLimits(0.0, 0.0, 1.0);
  slider6.setEasing(4.0);
  slider6.setNumberFormat(G4P.DECIMAL, 2);
  slider6.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  slider6.setOpaque(false);
  slider6.addEventHandler(this, "slider6_change1");
  textfield1 = new GTextField(this, 60, 586, 90, 30, G4P.SCROLLBARS_NONE);
  textfield1.setText("16");
  textfield1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  textfield2 = new GTextField(this, 460, 475, 90, 30, G4P.SCROLLBARS_NONE);
  textfield2.setText("16");
  textfield2.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  slider7 = new GSlider(this, 460, 350, 200, 40, 10.0);
  slider7.setShowValue(true);
  slider7.setShowLimits(true);
  slider7.setLimits(0.0, -1.0, 1.0);
  slider7.setNumberFormat(G4P.DECIMAL, 2);
  slider7.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  slider7.setOpaque(false);
  slider7.addEventHandler(this, "slider7_change1");
  slider8 = new GSlider(this, 460, 386, 200, 50, 10.0);
  slider8.setShowValue(true);
  slider8.setShowLimits(true);
  slider8.setLimits(0.0, -1.0, 1.0);
  slider8.setNumberFormat(G4P.DECIMAL, 2);
  slider8.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  slider8.setOpaque(false);
  slider8.addEventHandler(this, "slider8_change1");
  slider9 = new GSlider(this, 460, 422, 200, 50, 10.0);
  slider9.setShowValue(true);
  slider9.setShowLimits(true);
  slider9.setLimits(0.0, -1.0, 1.0);
  slider9.setNumberFormat(G4P.DECIMAL, 2);
  slider9.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  slider9.setOpaque(false);
  slider9.addEventHandler(this, "slider9_change1");
}

// Variable declarations 
// autogenerated do not edit
GSlider slider1; 
GLabel label1; 
GSlider slider2; 
GSlider slider3; 
GSlider slider4; 
GSlider slider5; 
GSlider slider6; 
GTextField textfield1; 
GTextField textfield2; 
GSlider slider7; 
GSlider slider8; 
GSlider slider9; 
